# Generated by Django 5.2.6 on 2025-09-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='commodity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
