# Generated by Django 5.2.6 on 2025-09-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_commodity_alter_trip_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routewaypoint',
            name='location',
        ),
    ]
