# Generated by Django 5.2.6 on 2025-09-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='last_updated',
        ),
    ]
