# Generated by Django 5.2.6 on 2025-09-18 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('locations', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_zone', models.CharField(max_length=50)),
                ('shipping_document', models.CharField(blank=True, max_length=100, null=True)),
                ('commodity', models.CharField(blank=True, max_length=100, null=True)),
                ('total_drive_time', models.IntegerField(default=0)),
                ('total_on_duty_time', models.IntegerField(default=0)),
                ('cycle_hours_used', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_logs', to='drivers.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hos_logs', to='trips.trip')),
            ],
            options={
                'verbose_name_plural': 'HOS Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('driving', 'Driving'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('hos_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_periods', to='logs.hoslog')),
            ],
            options={
                'verbose_name_plural': 'Duty Periods',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='HOSViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('daily_drive_limit', 'Daily Drive Limit Exceeded'), ('daily_on_duty_limit', 'Daily On-Duty Limit Exceeded'), ('cycle_limit', 'Cycle Limit Exceeded'), ('break_required', 'Break Required')], max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('violation', 'Violation')], default='warning', max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('hos_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='logs.hoslog')),
            ],
            options={
                'verbose_name_plural': 'HOS Violations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
