# Generated by Django 5.2.6 on 2025-09-18 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_violations', models.IntegerField(default=0)),
                ('violations_by_type', models.JSONField(default=dict)),
                ('driver_compliance_scores', models.JSONField(default=dict)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
